from app.models.paziente import Paziente
from app.models.medico import Medico
from app.models.specializzazione import Specializzazione
from app.models.ambulatorio import Ambulatorio
from app.models.segreteria import Segreteria
from app.models.orario_ricevimento import OrarioRicevimento
from app.models.assenza import Assenza
from app.models.fascia_oraria_visita import FasciaOrariaVisita
from app.models.prenotazione import Prenotazione
from app.models.log_attivita import LogAttivita
from app.models.impostazioni_clinica import ImpostazioniClinica